<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="cuisine.xsl" type="text/xsl"?>

<!DOCTYPE cuisine [
<!ELEMENT cuisine           (cuisineType, restaurant+)>
<!ELEMENT restaurant        ( logo?
                            , picture+
                            , address
                            , phoneNo+
                            , openingHours
                            , delivery
                            , description
                            , rating?
                            , gpsCoordinates?)
>
<!ELEMENT cuisineType       EMPTY>
<!ELEMENT logo              (#PCDATA)>
<!ELEMENT picture           (#PCDATA)>
<!ELEMENT address           EMPTY>
<!ELEMENT phoneNo           (#PCDATA)>
<!ELEMENT openingHours      (openTimes+)>
<!ELEMENT openTimes         (openTime, closeTime)>
<!ELEMENT openTime          (time)>
<!ELEMENT closeTime         (time)>
<!ELEMENT time              EMPTY>
<!ELEMENT delivery          (minimumPrice, fee)>
<!ELEMENT minimumPrice      EMPTY>
<!ELEMENT fee               EMPTY>
<!ELEMENT description       (#PCDATA)>
<!ELEMENT gpsCoordinates    EMPTY>

<!ATTLIST restaurant        name        CDATA   #REQUIRED>
<!ATTLIST restaurant        url         CDATA   #REQUIRED>
<!ATTLIST restaurant        openDays    CDATA   #REQUIRED>
<!ATTLIST restaurant        rating      CDATA   #IMPLIED>
<!ATTLIST cuisineType       type        (Asian
                                                | BBQandGrill
                                                | Burger
                                                | Indian
                                                | Italian
                                                | Thai)
                                                #REQUIRED
>
<!ATTLIST address           streetNo    CDATA   #REQUIRED>
<!ATTLIST address           streetName  CDATA   #REQUIRED>
<!ATTLIST address           city        CDATA   #REQUIRED>
<!ATTLIST address           zipCode     CDATA   #REQUIRED>
<!ATTLIST phoneNo           type        CDATA   #REQUIRED>
<!ATTLIST openDays          day         CDATA   #REQUIRED>
<!ATTLIST openTimes         day         CDATA   #REQUIRED>
<!ATTLIST time              amPm        (am|pm) #REQUIRED>
<!ATTLIST time              hours       CDATA   #REQUIRED>
<!ATTLIST time              minutes     CDATA   #REQUIRED>
<!ATTLIST minimumPrice      dollars     CDATA   #REQUIRED>
<!ATTLIST minimumPrice      cents       CDATA   #REQUIRED>
<!ATTLIST fee               dollars     CDATA   #REQUIRED>
<!ATTLIST fee               cents       CDATA   #REQUIRED>
<!ATTLIST gpsCoordinates    latitude    CDATA   #REQUIRED>
<!ATTLIST gpsCoordinates    longitude   CDATA   #REQUIRED>

<!ENTITY as     "Asian">
<!ENTITY bq     "BBQandGrill">
<!ENTITY bu     "Burger">
<!ENTITY in     "Indian">
<!ENTITY it     "Italian">
<!ENTITY th     "Thai">
<!ENTITY mon    "Monday">
<!ENTITY tue    "Tuesday">
<!ENTITY wed    "Wednesday">
<!ENTITY thu    "Thursday">
<!ENTITY fri    "Friday">
<!ENTITY sat    "Saturday">
<!ENTITY sun    "Sunday">
]>

<cuisine>
    <cuisineType type="&bu;"/>
    <restaurant name="Bob&#39;s Burgers" url="http://www.bobsburgers.com.au/" openDays="&mon;&#45;&sun;"
     rating="5">
        <picture>images/cheeseburger.jpg</picture>
        <address streetNo="1956" streetName="George Avenue" city="Manly" zipCode="1515"/>
        <phoneNo type="Office">2513917430</phoneNo>
        <openingHours>
            <openTimes day="&mon;&#45;&fri;">
                <openTime>
                    <time amPm="am" hours="06" minutes="00"/>
                </openTime>
                <closeTime>
                    <time amPm="pm" hours="08" minutes="00"/>
                </closeTime>
            </openTimes>
            <openTimes day="&sat;&#45;&sun;">
                <openTime>
                    <time amPm="pm" hours="05" minutes="00"/>
                </openTime>
                <closeTime>
                    <time amPm="pm" hours="10" minutes="00"/>
                </closeTime>
            </openTimes>
        </openingHours>
        <delivery>
            <minimumPrice dollars="01" cents="50"/>
            <fee dollars="05" cents="00"/>
        </delivery>
        <description>
            Bob&#39;s Burgers are the best in town. Choose your own ingredients&#33;
        </description>
        <gpsCoordinates latitude="&#45;32.414763" longitude="151.030145"/>
    </restaurant>

    <restaurant name="Man Burgers" url="http://www.manburgers.com.au/" openDays="&mon;&#45;&fri;"
     rating="4">
        <picture>images/manlyburger.jpg</picture>
        <address streetNo="3126" streetName="Gambler Lane" city="Hornsby" zipCode="1400"/>
        <phoneNo type="Office">2818681222</phoneNo>
        <phoneNo type="Customer Service">2816909298</phoneNo>
        <openingHours>
            <openTimes day="&mon;&#45;&fri;">
                <openTime>
                    <time amPm="am" hours="08" minutes="00"/>
                </openTime>
                <closeTime>
                    <time amPm="pm" hours="08" minutes="00"/>
                </closeTime>
            </openTimes>
        </openingHours>
        <delivery>
            <minimumPrice dollars="02" cents="50"/>
            <fee dollars="04" cents="00"/>
        </delivery>
        <description>The manliest burgers in Australia.</description>
    </restaurant>

    <restaurant name="24&#47;7 Burgers" url="http://www.247burgers.com/" openDays="&mon;&#45;&sun;"
     rating="2">
        <logo>images/247BurgersLogo.jpg</logo>
        <picture>images/beefburger.jpg</picture>
        <address streetNo="1712" streetName="Plainfield Avenue" city="Bankstown" zipCode="1035"/>
        <phoneNo type="Office">3155691854</phoneNo>
        <openingHours>
            <openTimes day="&mon;&#45;&sun;">
                <openTime>
                    <time amPm="am" hours="00" minutes="00"/>
                </openTime>
                <closeTime>
                    <time amPm="pm" hours="11" minutes="59"/>
                </closeTime>
            </openTimes>
        </openingHours>
        <delivery>
            <minimumPrice dollars="00" cents="00"/>
            <fee dollars="00" cents="00"/>
        </delivery>
        <description>Open 24&#47;7. Got your burgers at any time. Free delivery.</description>
    </restaurant>
</cuisine>
